#include "strXele.h"
#include <algorithm>
#include <cstdio>
#include <cstring>
#include <iterator>

namespace {

static thread_local char freeBuf[512];

static constexpr unsigned short kXeleErrorNums[] = {
    0,
    202,
    203,
    204,
    208,
    209,
    211,
    212,
    213,
    214,
    215,
    216,
    217,
    218,
    219,
    220,
    222,
    223,
    224,
    225,
    226,
    227,
    228,
    231,
    234,
    236,
    237,
    243,
    244,
    245,
    246,
    247,
    248,
    250,
    252,
    253,
    257,
    263,
    264,
    265,
    266,
    267,
    268,
    269,
    270,
    271,
    272,
    273,
    274,
    275,
    276,
    277,
    278,
    279,
    280,
    281,
    282,
    283,
    401,
    403,
    404,
    405,
    406,
    407,
    408,
    409,
    410,
    411,
    412,
    413,
    499,
    731,
    732,
    733,
    734,
    735,
    736,
    752,
    753,
    754,
    755,
    756,
    757,
    758,
    759,
    1005,
    1021,
    1022,
    1023,
    1024,
    1025,
    1026,
    1027,
    1028,
    1029,
    1030,
    1031,
    1034,
    1039,
    1043,
    1050,
    1100,
    1101,
    1102,
    2000,
    2001,
    2004,
    2006,
    2007,
    2008,
    2101,
    2102,
    4012,
    5000,
    5001,
    5002,
    5003,
    5004,
    5005,
    5006,
    5007,
    5008,
    5009,
    5010,
    5011,
    5012,
    5013,
    5014,
    5015,
    10000,
    10004,
    10008,
    10018,
    10100,
    10106,
    10236,
    10252,
    10262,
    10266,
    10280,
    10444,
    10450,
    10476,
    10508,
    10512,
    10516,
    10560,
    10562,
    10596,
    10610,
    10702,
    10706,
    10708,
    10712,
    10740,
    10796,
    10804,
    10806,
    10812,
    10836,
    10930,
    10932,
    11034,
    11038,
    11040,
    11042,
    11050,
    11060,
    11064,
    11068,
    11080,
    11082,
    11098,
    11128,
    11130,
    11150,
    11152,
    11166,
    11202,
    11218,
    11220,
    11228,
    11236,
    11238,
    11240,
    11246,
    11266,
    11268,
    11270,
    11278,
    13304,
    13338,
    13360,
    13374,
    13398,
    13424,
    13430,
    13434,
    13440,
    13446,
    13448,
    13454,
    13456,
    13458,
    13518,
    13582,
    13586,
    13588,
    13592,
    18200,
    18202,
    18206,
    19036,
    19058,
    19112,
    19114,
    19128,
    20000,
    20001,
    20002,
    20003,
    20004,
    20005,
    20006,
    20007,
    20008,
    20009,
    20010,
    20011,
    20012,
    20013,
    20014,
    20015,
    20016,
    20017,
    20018,
    20019,
    20020,
    20021,
    20022,
    20023,
    20024,
    20025,
    20026,
    20027,
    20028,
    20029,
    20030,
    20031,
    20032,
    20033,
    20034,
    20035,
    20036,
    20037,
    20038,
    20039,
    20040,
    20041,
    20042,
    20046,
    20047,
    20048,
    20049,
    20050,
    20051,
    20055,
    20056,
    20059,
    20060,
    20061,
    20062,
    20063,
    20064,
    20065,
    20067,
    20068,
    20069,
    20070,
    20071,
    20073,
    20074,
    20075,
    20076,
    20077,
    20078,
    20079,
    20095,
    20096,
    20097,
    20099,
    20101,
    20102,
    20103,
    20104,
    20105,
    20106,
    20107,
    20108,
    20110,
    20111,
    20112,
    20113,
    20114,
    20115,
    20116,
    20117,
    20118,
    20119,
    20120,
    20121,
    20122,
    20123,
    20124,
    20125,
    20126,
    20127,
    20128,
    20129,
    20130,
    20131,
    20132,
    20133,
    20134,
    20135,
    20136,
    20137,
    20138,
    20139,
    20140,
    29995,
    29996,
    29997,
    29998,
    29999,
    55002,
    55003,
    55005,
    55007,
    55014,
    55015,
    55016,
    55020,
    55021,
    55031,
    55033,
    55037,
    55038,
    55039,
    55040,
    55041,
    55042,
    55043,
    55044,
    55045,
    55046,
    55047,
    55048,
    55049,
    55050,
    55052,
    55053,
    55054,
    55055,
    55056,
    55057,
    55058,
    55059,
    55060,
    55061,
    55062,
    55063,
    55064,
    55065,
    55067,
    55068,
    55069,
    55070,
    55071,
    55072,
    55073,
    55074,
    55075,
    55076,
    55077,
    55078,
    55079,
    55080,
    55081,
    55082,
    55083,
    55084,
    55085,
    55086,
    60000,
    60001,
    60002,
    60003,
    60004,
    60005,
    60006,
    60007,
    60008,
    60009,
    60010,
    60011,
    60012,
    60013,
    60014,
    60015,
    60016,
    60017,
    60018,
    60019,
    60020,
    60021,
    60022,
    60023,
    60024,
    60025,
    60026,
    60027,
    60028,
    60029,
    60030,
    60031,
    60032,
    60033,
    60034,
    60035,
    60036,
    60037,
    60038,
    60039,
    60040,
    60041,
    60042,
    60043,
    60044,
    60045,
    60046,
    60047,
    60048,
    60049,
    60050,
    60051,
    60052,
    60053,
    60054,
    60055,
    60056,
    60057,
    60058,
    60059,
    60060,
    60061,
    60062,
    60063,
    60064,
    60065,
    60066,
    60067,
    60068,
    60069,
    60070,
    60071,
    60072,
    60073,
    60074,
    60075,
    60076,
    60077,
    60078,
    60079,
    60080,
    60081,
    60082,
    60083,
    60084,
    60085,
    60086,
    60087,
    60088,
    60089,
    60090,
    60091,
    60092,
    60093,
    60094,
    60095,
    60096,
    60097,
    60098,
    60099,
    60100,
    60101,
    60102,
    60103,
    60104,
    60105,
    60106,
    60107,
    60108,
    60109,
    60110,
    60111,
    60200,
    60201,
    60202,
    60203,
    60204,
    60205,
    60206,
    60207,
    60208,
    60209,
    60210,
    60211,
    60212,
    60213,
    60214,
    60215,
    60216,
    60217,
    60218,
    60220,
    60221,
};

static constexpr const char *const kXeleErrorStrs[] = {
    "正确 OK",
    "无效操作员代码 Invalid PBU",
    "无效证券代码 Invalid SecuritiesID",
    "申报时间为该证券的非交易时间 Non-trading time",
    "无效买卖标志，非‘B’或者‘S’ Invalid Direction",
    "交易品种不对 Wrong contract group",
    "此账号不能进行该证券交易 This contract unavailable for this account",
    "价格申报出错 Wrong request price",
    "证券已被挂起 Securities suspended",
    "该股票不参与集合竞价 The stock not participant in aution",
    "无效帐号 Invalid AccountID",
    "该帐号未指定在你席位 The account not assigned to your seat",
    "帐号已被挂起 Account has been suspended",
    "无效申报价格 Invalid request price",
    "申报价不能为零 Price can not be 0",
    "申报价格不符合最小价格步长要求 Price not meet the minimum step",
    "申报价格超出范围 Price out of range",
    "申报买入数量必须是1000的整数倍 Volume must be an integer multiple of 1000",
    "无效的申报数量 Invalid volume",
    "申报数量必须大于0 Volume must be greater than 0",
    "新股申报数量至少1000 New shares Volume at least 1000",
    "申报数量不符合最小步长要求 Volume not meet the minimum step",
    "申报数量超过单笔最大允许申报的上限 Volume exceeds the maximum allowable bid limit",
    "账号可卖出的余额不足 Insufficient balance",
    "股票持有量超出限量 Position exceeds the limit",
    "PBU没有买入权限 PBU has no permission to buy",
    "PBU没有卖出权限 PBU has no permission to sell",
    "基金帐号/机构帐号不能买卖此证券 Fund account or institution account can not buy or sell this securities",
    "'S'帐号不能买入 'S' account can not buy",
    "不能撤销指定（有卖空股票，请先补回卖空股票） can not cancel",
    "不能撤销指定（有申报） can not cancel",
    "不能撤销指定（公司卖空） can not cancel",
    "中国证券登记结算公司不允许撤销指定 Cannel not allowed by CSDC",
    "B股结算会员代码（数据库接口中的firmid）错，可从中登公司上海分公司查询。 Wrong B-share firmid",
    "无效操作员代码 Invalid PBU",
    "操作员权限不够 No permission",
    "操作员申报的rec_num序号不连续 Discontinuous rec_num",
    "市价订单不参加集合竞价 Market orders not participate in auction",
    "最优五档即时成交剩余撤销市价订单对手方无未成交订单 Counterparty has no unsettled orders",
    "最优五档即时成交剩余转限价市价订单对手方和本方均无未成交订单 The counterparty and the party have no unsettled orders",
    "该券种不允许做市价订单 This securities group not allowed for market order",
    "帐户没有权限进行账户式质押回购的交易及出入库 Account has no permission to process account-style pledge repurchase transactions and deposits and withdrawals",
    "场内报盘对于出入库申报的统一出错代码 Uniform error codes for out-put and in-put of warehouse",
    "申报类型错误 Wrong OrderType",
    "申报类型错误 Wrong OrderType",
    "该帐号已指定在你席位 The accounthas assigned to your seat",
    "未做指定不能交易 Can not trade without specified participants",
    "E 帐号不能通过场内申报进行交易 Account not be traded through floor offers",
    "信用交易的申报帐户必须是E 帐户 The reporting account for credit transactions must be an E-account",
    "普通交易的申报帐户必须不是E 帐户 The reporting account for ordinary transactions must not be an E-account",
    "该证券不允许担保品买入 The Securities not support trading with collateral",
    "信用卖出权限不足 Insufficient permission for credit selling",
    "该证券不允许融资买入 Not allow to buyby financing",
    "卖券还款或融资平仓权限不足 Insufficient permission to repay by selling securities or finance by liquidating",
    "买券还券或融券平仓权限不足 Insufficient permission to return by buying or margin trading by liquidating",
    "该证券不允许融券卖出 The securities are not allowed to be sold for margin selling",
    "融券卖出申报价格低于最新成交价 The margin selling price is lower than the latest price",
    "买券还券、融券卖出、融券平仓申报的信用帐户必须配置证券公司融券专用帐户 Special account must be configured for special business",
    "无效操作员代码 Invalid PBU",
    "无效申报序号 Invalid rec_num",
    "撤单对应申报序号检验失败 The rec_num of cancelled order checked failed",
    "撤单对应的证券帐号检验失败 The stock account of cancelled order checked failed",
    "撤单对应的股票代码检验失败 The SeciritiesID of cancelled order checked failed",
    "撤单对应的买卖方向检验失败 Direction of cancelled order checked failed",
    "对应的申报已经被撤单 Order has been cancelled",
    "只能通过买799998撤销指定 Can only be cancelled by buying 799998",
    "只能通过买799999重新指定 Can only be cancelled by buying 799999",
    "对应的申报已成交，不能撤单 The corresponding bid has been completed and the order can not be cancelled",
    "不允许撤单 Cancell not allowed",
    "撤单失败,对应的申报已成交或者已经被撤单 Cancel order failed, the order was traded or cancelled",
    "无申报可撤 None can be cancelled",
    "基金公司未上传ETF申购赎回清单 Fund companies not upload ETF purchase redemption list",
    "ETF状态不对 Wrong ETF status",
    "ETF投资者持股不足 ETF investors have insufficient Position",
    "ETF现金替代比例超过基金公司规定的比例 Substitution Ratio of ETF cash exceed the ratio ruled",
    "ETF基金账号持股余额不足，投资者不能赎回 Insufficient balance, can not redeem",
    "ETF基金账户不能申购或赎回 ETF fund account not buy or redeemed",
    "账户中没有现券 No cash coupons in this account",
    "账户中现券余额不足 Insufficient cash coupons in this account",
    "账户中没有标准券 No standard coupons in this account",
    "账户中标准券余额不足 Insufficient standard coupons in this account",
    "账户没有质押券 No pledged bonds in this account",
    "账户的质押券余额不足 Insufficient pledged coupons int this account",
    "标准券折算率未初始化 Conversion rate of standard coupon not initialized",
    "标准券代码不存在 Standard coupons code not exist",
    "登录主机失败 Login to host failed",
    "rec_num 必须连续递增 Discontinuous rec_num",
    "股票代码错误或者非本市场产品 Wrong SecuritiesID or non-market products",
    "账号错误 Wrong Account ID",
    "买卖方向错误 Wrong Direction",
    "价格错误 Wrong Price",
    "数量错误 Wrong Volume",
    "日期错误 Wrong Date",
    "申报单或撤消单的标志错误 Wrong sign for order or cancel order",
    "结算会员代码错误 Wrong clearing member ID",
    "撤消单的ordrec域错误 Wrong ordrec domain of cancel order",
    "撤消单的ordrec域大于等于撤消单的rec_num域 Ordrec field of the cancel order greater than or equal to the rec_num field of the cancel order",
    "撤消的申报单是失败的数据单 Cancelled order discarded",
    "刚读入待处理的单子的status是’ P’或’p’ The status of order is 'P' or 'p' 1040刚读入待处理的单子的status不是’ R’，也不是’P’ The status of order is neither 'P' nor 'p' 1042 底层通讯接收时发生错 An error occurred while communicating",
    "接收到的数据包内容错误 Wrong received packet",
    "撤消的申报单不存在或者撤单申报的证券代码错误 The cancelled order not exist or SecuritiesID of the cancelled order wrong",
    "申报号太大 The offer number too large",
    "记录不匹配 Records mismatch",
    "营业部代码格式错误，格式必须为 1到65535的整数 Wrong format of business branchID",
    "与交易所的网络连接出错 Connect to exchange failed",
    "被撤单的日期不是今天 Date of the cancelled order not today",
    "被撤单的帐号不是本人 Account which cancels order not mine",
    "撤单记录中被撤单的股票代码与被撤单不一致 SecuritiesID of the cancelled order in recordinconsistent with the cancelled order",
    "撤单记录中被撤单的股票价格不正确，与被撤单不一致 Price of the cancelled order in record inconsistent with the cancelled order",
    "只有申报才可被撤单 Can only cancel order which exists",
    "撤单记录和被撤单记录的股票买卖方向不同 Wrong Directionof cancelled order",
    "撤单记录和被撤单记录的股票数量不同 Wrong Volume of cancelled order",
    "错误的证券代码和BizID Wrong securityID or wrong BizID",
    "信息长度超过4k Message exceed mas length 4k",
    "校验码错误 CheckSum error",
    "心跳超时 HeartBeat timeout",
    "已经登录 Already login",
    "登录超时 Login timeout",
    "CompId错误 CompId error",
    "未准备 Not ready",
    "网络错误 Internal error",
    "信息类型不合法 Message type illegal",
    "不接受新报单 Do not Accept new order",
    "setID错误 Wrong setID",
    "Pbu错误 Wrong Pbu",
    "先登录 Login first",
    "BeginReportIndex错误 Wrong BeginReportIndex",
    "不支持prtcl版本 Unsupported prtcl version",
    "信息错误 Message data error",
    "未明错误 Unspecified error",
    "无效密码 Invalid password",
    "无效交易代码 Invalid transaction code",
    "无效市场类型 Invalid market type",
    "无效的产品子类型 Invalid product subtype",
    "无效的产品类型 Invalid instrument type",
    "无效时间戳 Invalid time stamp",
    "该交易时段内禁用该功能 Disable this function during this trading period",
    "无效的报单类型 Invalid order type",
    "无效的交易限制类型 Invalid trading restriction type",
    "不合理的数量 Unreasonable quantity",
    "报单数量超过最低限度 Order quantity exceeds lower limit",
    "报单价格超过范围 Order price exceeds range",
    "无效的pbu类型 Invalid pbu type",
    "交易员处于不活动状态 Inactive pbu",
    "PBU交易标识为未激活（暂停状 PBU has no permission态，权限不足）",
    "交易员处于不活动状态 Inactive PBU",
    "买订单数量不是最小单位的整数倍 Buy order quantity not round by lotsize",
    "卖订单数量不是最小单位的整数倍 Sell order quantity not round by lotsize",
    "订单价格不是增加单位的整数倍 Order price not round by ticksize",
    "订单没有找到 Order not found",
    "投资者帐户与PBU无指定交易关系 Investor account not designated to the PBU",
    "投资者帐户已被暂停 Investor account is suspended",
    "投资者帐户类型对该产品无效 Invalid AccountID type for this product",
    "无效的投资者账户 Invalid investor account id",
    "交易时间已经结束 Trading phase already finished",
    "该帐户类型不允许指定 Account type not allowed to be specified",
    "该帐号已指定在其它席位 Account has assigned to other seats",
    "该帐户类型不允许撤销指定 Account type not allowed to cancel",
    "指定的交易不存在 Designated trading not exist",
    "投资者持仓不足 Investor holding position not enough",
    "不正确的市场状态 Wrong market status",
    "当前时间阶段不允许报单 Order not allowed in current phase",
    "该产品此非交易类型业务今日不开放 Non-transaction business of this product not open today",
    "无效的分红选择 Invalid dividend selection",
    "无效的转托管来源或目的 Invalid trusteeship source or purpose",
    "该业务申报不可用 Business not available",
    "投资者持仓不存在 Investor holding position not exist",
    "该PBU没有该产品的买权限 PBU doesn't have buy right for the instrument",
    "该PBU没有该产品的卖权限 PBU doesn't have sell right not the instrument",
    "该PBU无权限交易此产品 PBU has no permission to trade",
    "该账户没有权限买此产品 Account doesn't have buy right for the instrument",
    "该账户没有权限卖此产品 Account doesn't have sell right for the instrument",
    "订单数量超过最高上限 Order quantity exceeds upper limit",
    "投资者无此非交易类型业务权限 Investors has no permissionto non-transaction business",
    "该产品此非交易类型业务已经被暂停 Non-transaction business suspended",
    "无效的转换基金 Invalid switching fund",
    "正在进行撤销指定（可能发生在联通PBU对该帐户进行撤销指定的同时，本PBU进行订单输入的场景；也可能发生在先输入一笔普通交易，然后输入一笔该帐户撤销指定交易的场景） Cancel of designation in progress",
    "该帐号已指定在其它席位 Account has been assigned to other seats",
    "无效PBU Invalid pbu",
    "不正确的信用标签类型 Wrong credit label type",
    "产品不能作为抵押品交易 Instrument can't be traded as collateral",
    "无效信用标签 Invalid credit tag",
    "该PBU无融资买入权限 PBU has no permission to buy",
    "该PBU无融券卖出权限 PBU has no permission to sell",
    "集合竞价最后五分钟不允许删除订单 Not allowed to delete order in the last five minutes of the auction",
    "交易阶段尚未准备好进行交易 Trading phase isn't ready for trade",
    "投资者无此类型产品买权限 Investors has no permission to buy",
    "投资者无此类型产品卖权限 Investors has no permission to sell",
    "重新提交订单 Resubmit order",
    "无效的广播重传请求范围 Invalid broadcast retransmission request range",
    "未上市的产品 Instrument not listed",
    "无效的订单类型和产品组合 Invalid OrderType and product combination",
    "不能在集合竞价时输入国债分销买单 Can not buy the national debt distribution order during the auction",
    "登录pbu处于不活跃状态 Login pbu is inactive",
    "禁止限价订单交易 Limit order forbidden",
    "超过集合竞价最大订单配置量 Exceed the maximum Volumeconfigured in the auction",
    "订单不匹配或者已删除 Order is matched or deleted",
    "撤单包含不一致的产品 Cancel order has an inconsistent instrument",
    "该证券不允许买券还券或融券平仓 Not allowed to return by buying or margin trading by liquidating",
    "无效的TDGW版本 Invalid tdgw version",
    "不允许出售抵押品、出售凭证、清算 Not allowed to Sell collateral, sell vouchers, liquidate",
    "禁止删除报单 Delete order is prohibited",
    "超过ETF赎回限额 Exceed ETF redemption limit",
    "交易主机忙 Trading host busy",
    "参数无效 Invalid parameter",
    "改变时间无效 Invalid change time",
    "恢复时间无效 Invalid resume time",
    "暂停时间无效 Invalid suspend time",
    "交易在未开始阶段，操作被禁止 Operation is prohibited in non-start phase",
    "包消息头已损坏 Package message header is broken",
    "无效的消息长度 Invalid message length",
    "无效的请求掩码 Invalid request mask",
    "无效的订单买卖方向 Invalid order side",
    "Biz PBU 和登录 PBU 属于不同的成员 Biz PBU and login PBU belongs different member",
    "Biz 类型无法获取 Biz type unavailable",
    "产品无法获取 Instrument unavailable",
    "PBU 无法获取 Pbu unavailable",
    "不被期待的消息类型 Message type unexpected",
    "无效的平台 ID Invalid platform id|无效账户 Invalid account:unopened account 账户为未开户账户",
    "无效的消息流 Invalid stream|无效账户 Invalid account:logged out; reported loss; etc. 账户是一个无效账户（已注销、挂失等等）",
    "PBU 重复登录 Pbu duplicate logon|无效账户 Invalid account:no transaction rights for the business product账户无对应业务产品的交易权限",
    "PBU 未登录 Pbu not logon",
    "业务禁止 Business prohibition:securities business switch off 证券的业务开关关闭",
    "业务禁止 Business prohibition:not allowed to declare this type of delegation当前阶段不允许申报该类委托",
    "证券停牌 Securities suspension证券停牌，不允许该类申报委托",
    "登录验证失败 Logon cerfication authenticated failed|价格错误 Wrong price委托价格不是价格档位的整数倍;网上发行认购价格不等于发行价;配股认购价格不等于配股价",
    "后端 PBU 启动 Pbu kickoff by backend|价格错误 Wrong price委托价格超过涨跌幅限制；盘后定价大宗交易委托价格不为指定价格；转融通证券出借委托的费率与公布的不一致",
    "无效的 clordid 格式 Invalid clordid format|数量非法 Wrong volume: Delegated quantity is not an integer multiple of quantity unit委托数量不是数量单位的整数倍；分级基金分拆合并委托数量非配比的整数倍",
    "无效的 origclordid 格式 Invalid origclordid format|非法数量 Illegal volume委托数量和金额都未满足最低交易门槛要求委托数量或金额超过上限;开放式基金申购未满足最低申购金额要求",
    "无效的 branchid 格式 Invalid branchid format|业务禁止 Business prohibition对折算率为 0 的证券不允许申报质押式回购质押申报；对非 A 股证券，成交申报业务子类别必须为非受限股份转让",
    "无效的 clearingfirm 格式 Invalid clearingfirm format|业务禁止 Business prohibition融资融券标的不存在或业务被禁止；申报转融通证券出借委托，证券代码和期限不在当天发布的标的范围内;证券代码不在当天发布的港股通标的范围内;证券代码不在股票质押式回购业务标的范围内",
    "无效的 userinfo 格式 Invalid userinfo format|业务禁止 Business prohibition证券当天集中竞价没有成交，不能申报以成交量加权平均价交易的委托",
    "无效的所有者类型 Invalid owner type|业务禁止 Business prohibition:margin trading is prohibited to declare market orders融券卖出禁止申报市价委托",
    "价格错误 Wrong price:commission price of margin selling not meet the price increase inspection requirements融券卖出委托价格不满足提价检查要求",
    "无效账户 Invalid account:credit account can only buy collateral securities信用账户只能买入担保品证券",
    "无效账户 Invalid account:non-credit account declaration financing and securities非信用账户申报融资融券委托 lending commission",
    "无效单元 Invalid unit债券分销业务中，卖委托的交易单元非承销商交易单元",
    "无效账户 Invalid account债券分销业务中，卖委托的证券账户非承销商证券账户或者买委托的证券账户为承销商证券账户",
    "数量超限 Quantity exceeded债券分销业务中，自行挂牌量超出自行挂牌总量",
    "股份卖空 Short selling持有股份不足;质押式报价回购初始交易数量大于可用标准券数量",
    "无效单元 Invalid unit委托的交易单元不存在；黄金 ETF 投资者交易单元找不到托管单元",
    "无效单元 Invalid unit:entrusted trading unit has no trading authority for the corresponding product委托的交易单元无对应产品的交易权限",
    "无效单元 Invalid unit:entrusted trading unit has no trading authority for the corresponding product委托的交易单元无对应业务的交易权限",
    "无效单元 Invalid unit信用账户必须通过信用交易单元申报；非信用账户必须通过非信用交易单元申报",
    "无效单元 Invalid unit:QFII account not declared from the designated trading unit QFII 账户未从指定交易单元申报",
    "无效单元 Invalid unit:trading unit has no business rights for the corresponding product交易单元无对应产品的业务权限",
    "业务禁止 Business prohibition:market participant business qualifications are restricted市场参与者业务资格被限制",
    "约定号重 Duplicate declaration number协议交易成交申报约定号重复",
    "配对失败 Pairing failed:declared elements of the two parties of the transaction not match交易双方申报要素不匹配",
    "配对失败 Pairing failed:B-share agreement trading domestic accounts and overseas accounts not be traded B 股协议交易境内账户和境外账户不能成交",
    "无对手方 No opponent协议交易点击成交申报约定号错误，未找到对应的定价申报",
    "金额非法 Illegal amount:amount in the commission must be an integer multiple of the amount unit委托中的金额必须为金额单位的整数倍",
    "申购不足 Insufficient subscription:insufficient investor stocks when purchasing ETFs申购 ETF 时投资者成份股不足",
    "赎回不足 Insufficient redemption:fund companies have insufficient stocks when redeeming ETFs赎回 ETF 时基金公司成份股不足",
    "现金超限 Cash overrun:cash replacement part exceeds the upper limit 现金替代部分超过上限",
    "无效账户 Invalid account合约账户标识码与申报交易单元对应的结算账号不一致；保证金查询指令中的结算账号与交易单元不匹配或交易单元无对应结算账号",
    "重复认购 Repeat subscription:reissue subscription online网上发行重复认购",
    "无效单元 Invalid unit非证券金融公司专用交易单元申报借入委托；证券金融公司专用交易单元申报出借委托；非金交所专用交易单元申报委托",
    "股份卖空 Short selling:corresponding pledged shares in the unsecured business are insufficient解押业务中对应的已质押股份不足",
    "股份卖空 Short selling:insufficient corresponding standard coupons in the discharge解押业务中对应的标准券不足",
    "无法成交 Unable to deal:market price order not meet the transaction conditions to cancel the order市价委托不满足成交条件撤单",
    "规模超限 Overrun基金累计申购或赎回总规模超限；质押式报价回购总规模超限;国际市场互联额度不可用",
    "规模超限 Overrun:single account fund cumulative purchase or redemption scale exceeds the limit单个账户基金累计申购或赎回规模超限",
    "规模超限 Overrun:fund's total net purchase or net redemption exceeds the limit基金净申购或净赎回总规模超限",
    "规模超限 Overrun:single account fund net purchase or net redemption scale exceeds the limit单个账户基金净申购或净赎回规模超限",
    "购回期限错误 Wrong buyback period:repurchase days exceeded business limit 回购天数超过业务限制",
    "无效会员 Invalid member:members have no transaction rights for the corresponding business会员无对应业务的交易权限",
    "无效账户 Invalid account:securities account for non-business designated transactions非业务指定交易的证券账户",
    "金额超限 Amount exceeded:net purchase amount exceeds the set limit当日净买入金额超出设定限额",
    "仓位不足 Insufficient positions期权构建组合申报时，成份合约单腿持仓不足;期权解除组合时，组合策略持仓不足或申报的组合流水号对应的持仓不存在",
    "交易量超限 Trading volume exceeded 超过投资者交易量限额",
    "持仓超限 Position limit exceeded 超过结算参与人持仓限额",
    "持仓超限 Position limit exceeded 超过投资者持仓限额",
    "资金不足 Insufficient funds:insufficient funds available for settlement participants结算参与人可用资金不足",
    "平台已关闭 Platform is closed 平台已关闭",
    "备兑标签错 Redemption label wrong备兑标签错误，只有卖开认购合约或买平认购合约时备兑标签可以为备兑",
    "结算机构错 Wrong settlement institution:billing agency code error结算机构代码错误",
    "无效账户 Invalid account:account under entrustment is a settlement restricted account委托中的账户为结算受限账户",
    "无效账户 Invalid account:account under commission is an unqualified account委托中的账户为不合格账户",
    "OwnerType 错误 Wrong OwnerType强平主动撤单的 OwnerType 必须与原委托的一致",
    "报价错误 Wrong quote:bid price declared by the bilateral quotation must be lower than the selling price双边报价申报的买价必须低于卖价",
    "无效业务 Invalid business:forced commission must be a limit order强平委托必须是限价委托",
    "报价撤销 Quote cancellation:quote is updated or withdrawn 报价被更新或撤销",
    "申报方式错误 Wrong declaration method竞价委托申报方式错误， TimeInForce 、 OrdType、 MaxPriceLevels、MinQty字段的组合不合法",
    "无报价权限 No quote authority:no market making authority无做市报价权限",
    "交易量超限 Trading volume exceeded:settlement participant transaction limit exceeded超过结算参与人交易量限额",
    "减持额度不足 Insufficient holdings:restriction of restricted shares; insufficient available quota受限股份减持，可用额度不足",
    "撤单请求错误 Wrong cancellation request主动撤单请求的 applid或证券 id 与原委托的不一致",
    "无法撤销 The order can not be cancelled 报单无法撤销",
    "委托不存在 Order not exist主动撤单未找到原始委托或者没有可以被撤销的报价",
    "重单 Repeat order 重单",
    "应用标识错 Wrong application identification 应用标识错误",
    "证券非法 Illegal securities:not support the declared business证券不支持所申报的业务",
    "解包失败 Unpacking failed 解包失败",
    "平台未开放 Platform not open 平台未开放",
    "交易单元错 Wrong trading unit:gateway no authority over the trading unit 网关对交易单元无权限",
    "字段错误 Wrong field 字段取值错误",
    "消息类型非法 Illegal message type:unsupported message type不支持的消息类型",
    "平台非法 Illegal platform:delegated platform error委托申报的平台错误，例如向现货集中竞价平台申报发行认购业务的委托",
    "价格类型错 Wrong price type:wrong price type 价格类型错误",
    "无效单元 Invalid unit:multi-party transaction unit in the transaction declaration not belong to the same member成交申报中的多方交易单元不属于同一会员",
    "无权限 No permission:gateway no authority to declare delegation网关无申报委托权限",
    "服务暂停 Service suspension:fund inquiry service suspended 资金查询服务暂停",
    "临时停市拒绝 Temporary market refusal:temporary market refusal 临时停市拒绝",
    "申报方式错误 Wrong bid成 交 申 报 报 文 TradeHandlingInstr 、 TradeReportTransType、 TradeReportType 字段组合不合法",
    "申报方式错误 Wrong bid:deal request originator error 成交请求发起方错误",
    "无效账户 Invalid account证券账户无三方回购业务的正/逆回购权限",
    "篮子非法 Illegal basketPledged bonds illegal三方回购申报的篮子个数超限；三方回购交易业务申报的篮子编号不在质押券篮子清单范围内",
    "质押券非法 Illegal Pledged bonds:number of pledged bonds declared by the three parties not meet the business requirements三方回购申报质押券个数不符合业务要求",
    "质押券非法 Illegal Pledged bonds三方回购初始交易申报的指定质押券不在申报的质押券篮子内; 三方回购补券申报的证券及换券申报的换入证券不在其对应的在途合约指定质押券篮子内",
    "质押券非法 Illegal Pledged bonds三方回购初始交易、补券、换券（仅换入）申报的指定质押券全天停牌",
    "质押券非法 Illegal Pledged bonds三方回购换券申报的换出证券不在其对应的在途合约质押券列表中",
    "无效单元 Invalid unit:counterparty trading unit in transaction declaration does not exist成交申报中的对手方交易单元不存在",
    "回购期限错误 Wrong buyback period三方回购初始交易指定质押券的到期日小于合约到期日；三方回购到期续做对应在途合约质押券到期日小于续做合约到期日",
    "合约不存在 Contract not exist三方回购到期购回、到期续做、提前购回、补券、换券未找到对应的在途合约",
    "业务禁止 Business prohibition三方回购到期购回、到期续做委托对应的在途合约不是当日到期合约；三方回购提前购回、换券、补券对应的在途合约不是未到期合约",
    "业务禁止 Business prohibition三方回购到期购回、到期续做、提前购回、补券、换券委托中交易单元、证券账户与对应在途合约中交易单元、证券账户不一致",
    "金额非法 Illegal amount三方回购到期续做金额超过原合约金额；三方回购提前购回金额小于原合约金额；三方回购解除质押金额（场内结算）小于原合约金额",
    "证券非法 Illegal securities三方回购入库证券不在质押券篮子清单范围内；期权构建、解除组合或行权指令合并申报时，成份合约标的证券与委托中 SecurityID 不一致",
    "无对手方 No opponent成交请求模式下确认方发起的委托未找到提交方申报的委托",
    "业务禁止 Business prohibition三方回购在途合约当前状态不允许申报该类别委托，比如已提前购回的合约不能再申报换券、补券委托，已对合约申报了到期购回，则不能再次申报到期购回或到期续做",
    "业务禁止 Business prohibition期权构建组合或行权指令合并申报时，合约的标的、合约单位、到期日不符规则",
    "业务禁止 Business prohibition:component contract passed the combination automatic release date成份合约已过组合自动解除日",
    "业务禁止 Business prohibition:contract not support the declared strategy合约不支持申报的策略",
    "业务禁止 Business prohibition期权构建组合或行权指令合并申报时，委托成份合约个数不符规则",
    "数量非法 Illegal quantity:number of entrusted component contracts not comply with the rules委托成份合约数量不符规则",
    "业务禁止 Business prohibition:entrusted component contract rights warehouse/obligatory warehouse not comply with the rules委托成份合约权利仓/义务仓不符规则",
    "业务禁止 Business prohibition期权构建组合或行权指令合并申报时，委托成份合约认购/认沽不符规则",
    "业务禁止 Business prohibition期权构建组合或行权指令合并申报时，委托成份合约行权价不符规则",
    "业务禁止 Business prohibition解除组合，申报的组合流水号对应组合策略持仓的参与人信息与委托中的不一致",
    "市场互联拒绝 Market interconnection rejection:Hong Kong Stock Connect's withdrawal request rejected by the Stock Exchange港股通撤单请求被联交所拒绝，具体拒绝原因代码见 RejectText",
    "市场互联拒绝 Market interconnection rejection:Hong Kong Stock Connect entrustment revoked by the Stock Exchange港股通委托被联交所自动撤销，具体撤销原因代码见 RejectText，撤销原因说明见 IMCRejectText",
    "市场互联拒绝 Market interconnection rejection:Hong Kong Stock Connect commission rejected by the Stock Exchange港股通委托被联交所拒绝，具体拒绝原因代码见 RejectText，拒绝原因说明见 IMCRejectText",
    "市场互联拒绝 Market interconnection rejection:Hong Kong Stock Connect commission rejected by the Stock Exchange港股通委托被联交所拒绝，具体拒绝原因代码见 RejectText，拒绝原因说明见 IMCRejectText",
    "其他错误 Other errors",
    "数据未填写 Empty filled information",
    "上次查询未结束 Last query did not end",
    "口令错误 Wrong password",
    "用户已登录 User already logined",
    "用户尚未登录 User not login",
    "系统内存不足 System Memory Not Enough",
    "错误的资金账号 Wrong AccountID",
    "投资者不合法，此操作不能被执行 Investor illegal,this operation can't be done",
    "不合法的密码 Illegal password",
    "错误的授权码 Wrong AuthCode",
    "登录子客户端索引错误 Login sub client index wrong",
    "资金账号不存在 AccountID not exist",
    "token 错误 Wrong token",
    "报单序号不是连续增加 The order number not increases monotonically",
    "被撤单找不到 Cancelled order not found",
    "交互式信息发送失败 Interactive msg send failed|内部进程间消息发送失败 Interactive msg send failed",
    "STEP 信息编码失败 STEP message encoded failed",
    "插入数据库失败 Failed to insert into database",
    "重复登录 Duplicate login",
    "柜台导上场数据初始化未完成 Initialization of settlement data not completed",
    "查询过快 Query too fast",
    "无相关记录 No relevant records",
    "登录超时 Login timeout",
    "该用户已经在其他链路登录 User has logged in on another link",
    "api 版本错误 Wrong API version",
    "接口未开启 Interface not open",
    "错误的时间格式 Wrong time format",
    "号段用尽或未配置号段 Number segment run out or not configured",
    "集中交易操作失败 Central trading operation failed",
    "用户登录 ip 检查失败 User login ip check failed",
    "用户登录 mac 地址检查失败 User login mac address check failed",
    "转移失败 Failed to transfer",
    "集中交易授权失败 Central trading authentication failed",
    "连接 headquarter错误 failed to connect to headquarter",
    "资金不能为负 Capital can not be negative",
    "系统 id 错误 Wrong system_id",
    "登录太快 Login too fast",
    "仓位检查错误 Position check failed",
    "组合策略类型错误 Wrong comb strategy type",
    "Zmq 通信错误 zmq failed",
    "已经有其他帐户登录到当前链接 Another account has already logged in this link",
    "发送到交易所失败 Send to Exchange Failed",
    "号码范围已用完 Number range is exhausted",
    "柜台正在数据恢复，等待完成 XeleTrade is recoverying, wait to be finished...",
    "取消其他账户订单 Cancel other account order",
    "重建失败 Rebuild Failed",
    "Xele-Bot 登录超时 Xele-Bot login timeout",
    "TransfereePbuID为空 TransfereePbuID is null",
    "号段结束值为空 Number range end is null",
    "转托管号段结束值为空 Number range redeposite_end is null",
    "没有配置非交易 tgw 通道 Do not have non-trade tgw session",
    "ClOrdID 超过号段范围 ClOrdID large than number range",
    "Order_sys_id 长度错误 Order_sys_id length error",
    "订单发送错误 DropOrder send err",
    "在转托管表中未找到 clordid Do not find clOrdID in table redeposite",
    "非交易链路未登录 Do not logon non-trade link",
    "强制撤单（正报单没发往交易所，被强制撤单） Forced cancellation",
    "委托权限校验失败 Operway check fail|Operway 检查失败 Operway check fail",
    "Api 监管信息检测失败 Api supervise information check fail",
    "正确 OK",
    "该合约限制买入 Contract restricts buy",
    "该合约限制卖出 Contract restricts sell",
    "该合约限制卖空 Contract restricts short selling",
    "不支持 Not support",
    "不允许跨市扫货单 Cross market scanning not allowed",
    "不允许市价单 Market orders not allowed",
    "价格超出范围 Price out of range",
    "单笔手数超过 ADV 限制 Volume exceeds adv limit",
    "报价最小值错误 Quotation minimum error",
    "单笔交易额过小 Single transaction volume too small",
    "单笔交易额过大 Single transaction volume too large",
    "单笔手数过小 Too small Volume",
    "单笔手数过大 Too large Volume",
    "当日用户报单 ID重复 Client order id Duplicate",
    "没找到合约 Contract not found",
    "不合法的有效期类型 Illegal validity type",
    "XeleTrade 停止交易 System stopped trading",
    "XeleTrade 限制交易 System restrict trading|XeleTrade 限制交易 System restricts to trade",
    "当日累计交易额过大 Accumulated trading volume of the day too large",
    "没有贷款经纪人标识 No loan broker logo",
    "报单速率过快 Order too fast",
    "报单表地址冲突 Order address conflict",
    "不合法的报单类型 Illegal Order Type",
    "不合法的报单方向 Illegal order direction",
    "不允许 IPO 交易 IPO transaction not allowed",
    "未成交单过多 Unsettled orders too many",
    "业务范围不正确 Incorrect business scope",
    "不允许有担保单的卖空 Short selling with guarantee not allowed",
    "不正确的最小价格变化值 Wrong minimum price unit",
    "不正确的最小手数单位 Wrong minimum lot unit",
    "报单不匹配或者报单表已满 Order not match or Order full",
    "缺失字段 Missing field",
    "超时(合约表不存在) System timeout",
    "字段错误 Field error",
    "改单时不允许增加，只能减少 Change order to increase not allow,to decrease allowed",
    "该机构不允许买入 Agency to buy not allowed",
    "该机构不允许卖出 Agency to sell not allowed",
    "该机构不允许卖空 Agency to short selling not allowed",
    "不允许自营买 Self buy not allowed",
    "不允许自营卖 Self sell not allowed",
    "不允许自营卖空 Self short selling not allowed",
    "完全不允许买 Restrict to buy",
    "完全不允许卖 Restrict to sell",
    "不允许卖空 Short sellling not allowed",
    "当天买入方向累计超额 Buy direction accumulated excess",
    "当天卖出方向累计超额 Sell direction accumulated excess",
    "卖出超出持仓 Sell exceeds position",
    "卖空超出借入 Short selling exceeds borrowing",
    "未应答报单 Unanswered order",
    "SAMSN 拒单 SAMSN refused",
    "VENUE 繁忙 VENUE busy",
    "该合约未成交买单超出上限 Contract unsettled and buy order exceeds the upper limit",
    "该合约未成交卖单超出上限 Contract unsettled and sell order exceeds the upper limit",
    "改单的合约不匹配 Modified contract not match",
    "该报单不存在 Order not exist",
    "报单查找表搜索超时 Order search timeout",
    "资金账户变化 Change of capital account",
    "数量错误 Quantity error",
    "该合约持仓过多 Contract positions too large",
    "该合约多头持仓过多 Holding long position of the contract too large",
    "该合约空头持仓过多 Holding short position of the contract too large",
    "售出手数大于可售手数 Sold lot greater than sellable lot",
    "可卖数量不足 Sellable quantity not enough",
    "可用资金量小于该笔报单保证金 Account balance less than margin of the order",
    "保证金占可用资金百分比过高 Ratio of margin occupying capital too large",
    "当天该合约撤单次数超限，不允许撤单 Cancel order not allowed",
    "客户报单 ID 与登录 ID 不一致 Customer order ID and login ID Inconsistent",
    "报单价格格式错误 Wrong format of order price",
    "报单价格条件字段不在枚举范围之内 Order price conditions field not in the range of enumeration",
    "报单买卖方向条件字段不在枚举范围之内 Condition of buy and sell direction field not in the range of enumeration",
    "报单开平字段不在枚举范围之内 Order field not in the range of enumeration",
    "报单投机套保标志字段不在枚举范围之内 Order speculative hedging mark field not in the range of enumeration",
    "报单有效期类型字段不在枚举范围之内 Order period of validity type field not in the range of enumeration",
    "报单操作标志字段不在枚举范围之内 Order operation flag field not in the range of enumeration|报单操作标志字 Order operation flag field not in the range of enumeration段不在枚举范围之内",
    "交易所端在途订单过多，限制报单 Number of order on the way too large",
    "xele_trade 系统高负载，报单过多，限制报单 System overload:qdr full",
    "xele_trade 系统高负载，持仓过多，限制报单 System overload:ddr full",
    "报单投机套保标志与客户交易类型不一致 Order speculative hedging mark inconsistent with customer transaction type",
    "交易所端流控达到上限 Flow control reach upper limit",
    "交易所端流控达到上限 Flow control reach upper limit",
    "交易所端流控达到上限 Flow control reach upper limit",
    "客户端未登录 Client not logged in",
    "报单已撤，不能再次撤销 Duplicate cancel",
    "拒绝自成交报单 Self closing order refused",
    "xele-monitor 强平单不能被用户通过 API 撤掉 Forced Liquidation order cannot be cancelled by API",
    "报单已经被撤掉了 Order has been withdrawn",
    "今日限买 Today buy limit",
    "合约格式错误 Contract format error",
    "成交量类型不在枚举范围内 Transaction type not in the range of enumeration",
    "触发条件不在枚举范围内 Trigger conditions not in the range of enumeration",
    "强平原因不在枚举范围内 Reasons for Liquidation order not in the range of enumeration",
    "报单手数小于最小成交量手数 Orders lot less than the minimum lot of transactions",
    "交易所端流控达到上限 Flow control reach upper limit",
    "交易所前置未准备 Exchange front not ready",
    "交易所前置错误 Exchange front error|前置错误 Exchange front error",
    "不允许开仓 Open position disallowed",
    "不允许期货 FOK报单 Futures FOK order not allowed",
    "IAS 格式错误 IAS format error",
    "交割月禁止开仓 Open position in delivery month disallowed",
    "未登录不允许交易 Trading not allowed without login",
    "系统负载过高 System overload",
    "限额达到最大值 Total bought amount reach the limit",
    "权利仓已达上限 Total bought underlying position reach the limit",
    "当日权利仓已达上限 Total today bought underlying position reach the limit",
    "总持仓已达上限 Total underlying position reach the limit",
    "禁止自成交 Self trade is forbidden",
    "触发价格偏离度风控 Trigger price deviation risk",
    "今天限卖 Today sell limit",
    "不允许撤单 Order not allowed withdraw",
    "新股配股报单只允许一次 Order insert only one time",
    "合约类型错误 SecurityType wrong",
    "报文 identification字段错误 Wrong identification field",
    "message_id 不再范围内 Message_id not in range",
    "message_len 错误 Wrong message_len",
    "用户报单 id 小于 maxorderid OrderID less than maxorderid|用户报单 id 小于 maxorderid 或超出范围 OrderID less than maxorderid or out of range",
    "报单方向错误 Wrong Direction",
    "positioneffect 不在范围内 Positioneffect not in range",
    "价格超出范围 Price out of system limit",
    "报单类型错误 Wrong OrderType",
    "时间条件错误 Wrong TimeCondition",
    "udp 校验错误 Wrong UDP check",
    "用户 token 错误 Wrong User token",
    "用户未登录 User not login",
    "web 报单不允许 api 撤单 Web order not allow api to cancel the order",
    "报单价格不能大于 10000 Order price cannot be greater than 10000",
    "号段前缀错误 Order Id prefix err",
    "号段 Id 错误 Order Id number err",
    "TCP 通道错误 Tcp Session Error",
    "合约类型错误 Securities Type Error",
    "被撤 SysID 超过号段范围 OrigSysID is out of number range",
    "报单资源已用尽 Order resource is exhausted",
    "订单价格不能小于 0 Order Price cannot be less than 0",
};


static constexpr const char *const kXeleMarketType[] = {
    "SH",
    "SZ",
    "OS",
    "OZ",
};

static constexpr const char *const kXeleOrderStatus[] = {
    "UNREPORT",
    "REPORTING",
    "REPORTED",
    "REPORTED_ACTION",
    "PTRADE_ACTION",
    "PACTION",
    "ACTIONED",
    "PTRADE",
    "TRADED",
    "ERROR",
};

static constexpr const char *const kXeleDirectionType[] = {
    "BUY",
    "SELL",
};

template <std::size_t N>
static const char *strLookUp(const char *const (&table)[N], int x) {
    if (x < 0 || x >= N) [[unlikely]] {
        int n = std::snprintf(freeBuf, 511, "%d", x);
        if (n >= 0) {
            freeBuf[n] = 0;
        } else {
            std::strcpy(freeBuf, "UNKNOWN_ERROR");
        }
        return freeBuf;
    }
    return table[x];
}

}

const char *strXeleMarketType(TXeleMarketType x) {
    if (x >= XELE_MARKET_SS) {
        x -= XELE_MARKET_SS;
    }
    return strLookUp(kXeleMarketType, x);
}

const char *strXeleOrderStatus(TXeleOrderStatusType x) {
    if (x >= ODRSTAT_UNREPORT) {
        x -= ODRSTAT_UNREPORT;
    }
    return strLookUp(kXeleOrderStatus, x);
}

const char *strXeleDirectionType(TXeleDirectionType x) {
    return strLookUp(kXeleDirectionType, x - XELE_ORDER_BUY);
}

const char *strXeleError(TXeleErrorIdType x) {
    if (x == 0) {
        return "OK";
    }

    if (x > 0 && x <= 65535) [[likely]] {
        auto it = std::lower_bound(std::begin(kXeleErrorNums), std::end(kXeleErrorNums), x);
        if (it != std::end(kXeleErrorNums) && *it == x) [[likely]] {
            return kXeleErrorStrs[it - std::begin(kXeleErrorNums)];
        }
    }

    int n = std::snprintf(freeBuf, 511, "E%d", x);
    if (n >= 0) {
        freeBuf[n] = 0;
    } else {
        std::strcpy(freeBuf, "UNKNOWN_ERROR");
    }
    return freeBuf;
}
